---
kind: pipeline
type: docker
name: default

.docker_build_settings_template: &docker_build_settings_template
    username:
        from_secret: DOCKER_LOGIN
    password:
        from_secret: DOCKER_PW
    repo: thecalcaholic/ncp-fork
    dockerfile: docker/debian-ncp/Dockerfile



steps:
- name: prepare-docker
  image: alpine:latest
  commands:
      - 'apk update && apk add bash jq git'
      - 'export version="$(git describe --tags --always)"'
      - 'version="$(bash -c "echo ${version%-*-*}")"'
      - 'echo "Found version: $version"'
      - '[[ -z "$version" ]] || echo "$version" >> .tags'

- name: build-docker-amd64
  image: plugins/docker
  settings:
      << : *docker_build_settings_template
      tags:
      - latest
      - test
      - donotuse
      - x86
      build_args:
      - "release=buster"
      - 'arch=amd64'
      - 'arch_qemu=x86_64'
  depends_on:
    - prepare-docker
trigger:
    branch:
    - master
    - devel
    - feature/**
...
