---
kind: pipeline
type: docker
name: default

steps:
- name: prepare-docker
  image: alpine:latest
  commands:
      - apk update && apk add bash jq
      - version="$(git describe --tags --always)"
      - version="${version%-*-*}"
      - echo "Found version: ${version}"
      - echo "$version" >> .tags

- name: build-docker-adm64
  image: plugins/docker
  settings:
      username:
          from_secret: DOCKER_LOGIN
      password:
          from_secret: DOCKER_PW
      repo: thecalcaholic/ncp-fork
      tags:
      - latest
      - test
      - donotuse
      - x86
      build_args:
      - "release=$(jq -r .release < etc/ncp.cfg)"
      - 'arch=amd64'
      - 'arch_qemu=x86_64'
      dockerfile: docker/debian-ncp/Dockerfile
trigger:
    branch:
    - master
    - devel
    - feature/**
...
