---
kind: pipeline
type: docker
name: default

.docker_build_settings_template: &docker_build_settings_template
    username:
        from_secret: DOCKER_LOGIN
    password:
        from_secret: DOCKER_PW
    repo: thecalcaholic/ncp-fork

.docker_build_commands: &docker_build_commands
  commands:
    #  - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker &
    - export VERSION="$(git describe --tags --always)"
    - export VERSION="${VERSION%-*-*}"
    - export RELEASE="$(jq -r .release < etc/ncp.cfg)"
    - echo "TAGS= ${PLUGIN_TAGS}"
    - echo "TAG= ${PLUGIN_TAG}"
    - echo "TAGS (file)= $([ ! -f '.tags' ] || cat .tags)"
    - echo "REPO= ${PLUGIN_REPO}"
    - echo "DAEMON OFF? ${PLUGIN_DAEMON_OFF}"
    - echo "BUILD ARGS= ${PLUGIN_BUILD_ARGS}"
    #  - DOCKER_BUILDKIT=1 docker build --progress=plain . -f "${DOCKERFILE}" -t "${REPO}:latest" --pull --build_arg arch="${ARCH}" --build_arg arch_qemu="${QEMU_ARCH}"
    #  - '[[ -z "$VERSION" ]] || docker tag "${REPO}:latest" "${REPO}:${VERSION}"'
    #  - docker tag "${REPO}:latest" "${REPO}:donotuse"

steps:
- name: prepare-docker
  image: alpine:latest
  commands:
      - 'apk update && apk add bash jq git'
      - 'version="$(git describe --tags --always)"'
      - 'version="${version%-*-*}"'
      - 'echo "Found version: ${version}"'
      - '[[ -z "$version" ]] || echo "$version" >> .tags'

- name: build-docker-amd64
  image: plugins/docker
  settings:
      << : *docker_build_settings_template
      tags:
      - latest
      - test
      - donotuse
      - x86
      build_args:
      - "release=buster"
      - 'arch=amd64'
      - 'arch_qemu=x86_64'
      dockerfile: docker/debian-ncp/Dockerfile
  depends_on:
      - prepare-docker
  << : *docker_build_commands

trigger:
    branch:
    - master
    - devel
    - feature/**
...
