---
kind: pipeline
type: docker
name: default

.docker_build_commands: &docker_build_commands
  commands:
    #  - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker &
    - env
    - echo "${REPO}"
    - apk add git jq
    - echo "user=$PLUGIN_USERNAME"
    - git fetch --tags
    - export VERSION="$(git describe --tags --always)"
    - export VERSION="${VERSION%-*-*}"
    - export RELEASE="$(jq -r .release < etc/ncp.cfg)"
    - export DOCKER_BUILDKIT=1
    - echo "${REPO}"; printenv REPO
    - echo "${ARCH}"
    - echo "${DOCKERFILE}"
    - echo "${RELEASE}"
    - echo "${QEMU_ARCH}"
    - dockerd-entrypoint.sh docker build --progress=plain . -f "${DOCKERFILE}" -t "${REPO}:latest" --pull --build_arg arch="${ARCH}" --build_arg arch_qemu="${QEMU_ARCH}" --build_arg release="${RELEASE}"
    #  - '[[ -z "$VERSION" ]] || docker tag "${REPO}:latest" "${REPO}:${VERSION}"'
    #  - docker tag "${REPO}:latest" "${REPO}:donotuse"

steps:
#- name: prepare-docker
#  image: alpine:latest
#  commands:
#      - 'apk update && apk add bash jq git'
#      - 'version="$(git describe --tags --always)"'
#      - 'version="${version%-*-*}"'
#      - 'echo "Found version: ${version}"'
#      - '[[ -z "$version" ]] || echo "$version" >> .tags'

- name: build-docker-amd64
  image: plugins/docker
  environment:
    ARCH: "amd64"
    ARCH_QEMU: "x86_64"
    DOCKERFILE: "docker/debian-ncp/Dockerfile"
    REPO: "thecalcaholic/ncp-fork"
    DOCKER_PW:
      from_secret: DOCKER_PW
    DOCKER_LOGIN:
      from_secret: DOCKER_LOGIN
    TAG:
      x86
    RELEASE: buster
#  depends_on:
#      - prepare-docker
  << : *docker_build_commands

trigger:
    branch:
    - master
    - devel
    - feature/**
...
