---
kind: pipeline
type: docker
name: default

.docker_build_env_template: &docker_build_env_template
    DOCKER_LOGIN:
        from_secret: DOCKER_LOGIN
    DOCKER_PW:
        from_secret: DOCKER_PW
    REPO: thecalcaholic/ncp-fork

.docker_build_commands: &docker_build_commands
- export VERSION="$(git describe --tags --always)"
- export VERSION="${VERSION%-*-*}"
- export RELEASE="$(jq -r .release < etc/ncp.cfg)"
- DOCKER_BUILDKIT=1 docker build --progress=plain . -f "${DOCKERFILE}" -t "${REPO}:latest" --pull --build_arg arch="${ARCH}" --build_arg arch_qemu="${QEMU_ARCH}"
- '[[ -z "$VERSION" ]] || docker tag "${REPO}:latest" "${REPO}:${VERSION}"'
- docker tag "${REPO}:latest" "${REPO}:donotuse"
    
steps:
- name: build-docker-amd64
  image: docker:dind
  environment:
      << : *docker_build_env_template
      ARCH: x86
      QEMU_ARCH: x86_64

trigger:
    branch:
    - master
    - devel
    - feature/**
...
